language: node_js

node_js:
  - node

script:
  - npm run test

deploy:
  - provider: npm
    email: laomao800@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: laomao800/parse-size-with-unit
